// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoeOkCNW4W5b9HR17ux806j8aDn_geUg',
    appId: '1:625836636601:web:7b16c1516a26005a141e68',
    messagingSenderId: '625836636601',
    projectId: 'loginappmovil-7f038',
    authDomain: 'loginappmovil-7f038.firebaseapp.com',
    storageBucket: 'loginappmovil-7f038.appspot.com',
    measurementId: 'G-5VCLD1R703',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPkVQdPPCQ_JfXnNCz5cjvTvYI3e32kN4',
    appId: '1:625836636601:android:999f69b424ea1925141e68',
    messagingSenderId: '625836636601',
    projectId: 'loginappmovil-7f038',
    storageBucket: 'loginappmovil-7f038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4W2hzQWbYKPqgy44Afx9HFjkSItPBwN4',
    appId: '1:625836636601:ios:3280ea8dab6984a7141e68',
    messagingSenderId: '625836636601',
    projectId: 'loginappmovil-7f038',
    storageBucket: 'loginappmovil-7f038.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4W2hzQWbYKPqgy44Afx9HFjkSItPBwN4',
    appId: '1:625836636601:ios:45d6ad2c6e2c9fc8141e68',
    messagingSenderId: '625836636601',
    projectId: 'loginappmovil-7f038',
    storageBucket: 'loginappmovil-7f038.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
